apiVersion: v2
name: act-runner
version: 0.1.2
description: Act runner for gitea actions
type: application
keywords:
  - gitea
  - actions
  - runner
  - cicd
home: https://github.com/proxfly/gitea-runner-charts
maintainers:
  - name: p
    email: gh.2lgqz@aleeas.com
    url: https://github.com/proxfly/gitea-runner-charts
appVersion: 0.2.6